### ISSUE TITLE
problem with setup.py

### ISSUE THREAD

**Issue by kurosh-z** [scottopell/aggdraw-64bits#2]
Hi,
I'm struggling to install aggdraw-64 for like a week but I still get a bunch of nonsense error!
could you please help me with this or lead me somewhere I could find the answer?
![capture](https://user-images.githubusercontent.com/32224317/36734702-952c1770-1bd4-11e8-9216-48d8c99ec03c.JPG)

```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
aggdraw.cxx:114:1: error: invalid conversion from ‘const char*’ to ‘Py_ssize_t {aka long int}’ [-fpermissive]
 };
 ^
aggdraw.cxx:114:1: error: invalid conversion from ‘destructor {aka void (*)(_object*)}’ to ‘printfunc {aka int (*)(_object*, _IO_FILE*, int)}’ [-fpermissive]
aggdraw.cxx:114:1: error: invalid conversion from ‘getattrfunc {aka _object* (*)(_object*, char*)}’ to ‘setattrfunc {aka int (*)(_object*, char*, _object*)}’ [-fpermissive]
aggdraw.cxx:132:1: error: invalid conversion from ‘const char*’ to ‘Py_ssize_t {aka long int}’ [-fpermissive]
 };
 ^
```

**Comment by scottopell** [comment]
I'm able to compile using gcc 7 and clang 9.

Not sure why you're seeing these errors.

What platform and what compiler are you using?

**Comment by kurosh-z** [comment]
I'm using Ubuntu subsystem on Windows! 
gcc 7 and clang 5 .
![capture](https://user-images.githubusercontent.com/32224317/36780037-248337a8-1c72-11e8-84f3-c227a6a4c568.JPG)

**Comment by kurosh-z** [comment]
by the way first I got this error with print : 
File "setup.py", line 25
    print "===", "freetype support disabled"
              ^
so I changed it to print ("==''), then I got what you saw before!
![error1](https://user-images.githubusercontent.com/32224317/36780283-d717ab10-1c72-11e8-9b8d-690b48c4545c.JPG)

**Comment by scottopell** [comment]
Ah, that probably means you're running it using python 3 to build this. I don't think that's supported. try it with python 2 and see if you get better results.

I unfortunately have no way of testing ubuntu subsystem on windows, so you might be on your own here.

**Comment by kurosh-z** [comment]
Thank you so much! That was exactly the problem. I thought there could be just a  problem with gcc cause all the errors I received was in cpp!

Just in case someone encounters the same problem here is what I've done :

Installing pip for pyhon2
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python2 get-pip.py

then this pip command : 

sudo python2 -m pip install git+https://github.com/scottopell/aggdraw-64bits@c95aac4369038706943fd0effb7d888683860e5a#egg=aggdraw

**Comment by scottopell** [comment]
Glad that worked!
