### ISSUE TITLE
Change prints to support python 3

### ISSUE THREAD

**Issue by fusir** [scottopell/aggdraw-64bits#3]
When you are on a system that prefers python3 by default its a real pain to run things in python2.

Fixing this problem is as easy as changing `print` to `print(`.  The vast majority of packages build succesfully without this problem because most packages have gotten up to date.  It's very important that we recognize open print as an anti pattern because it can break entire builds with just one package failing to conform to the positive pattern.

**Comment by scottopell** [comment]
Not a can of worms I want to open. I'm just hosting this on github for people's convenience.

Feel free to maintain your own python3 fork!
